name: Crear APK Android

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Obtener código
      uses: actions/checkout@v4

    - name: 2. Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: 3. Instalar Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.x'

    - name: 4. Instalar Flet
      run: |
        pip install -r requirements.txt
        pip install flet

    - name: 5. Compilar APK
      # Añadimos --icon para decirle qué imagen usar
      run: flet build apk --icon assets/icon.png --verbose

    - name: 6. Subir APK
      uses: actions/upload-artifact@v4
      with:
        name: AgendaLiz-App
        path: "**/*.apk"
